# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gb_messages.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gb_messages.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11gb_messages.proto\"\xeb\x01\n\x08LoraMsg2\x12\x17\n\x06status\x18\x01 \x02(\x0e\x32\x07.Status\x12\x12\n\nidentifier\x18\x02 \x02(\r\x12\x10\n\x08\x62uildnum\x18\x03 \x01(\r\x12\x0b\n\x03imu\x18\x04 \x01(\x0c\x12\x10\n\x08pressure\x18\x05 \x01(\r\x12\x13\n\x0btemperature\x18\x06 \x01(\x11\x12\x14\n\x0c\x62\x61tt_voltage\x18\x07 \x01(\r\x12\x11\n\tthreshold\x18\x08 \x01(\r\x12\x15\n\rconfiguration\x18\t \x01(\r\x12\x0c\n\x04rssi\x18\n \x01(\x11\x12\x1e\n\x06reprog\x18\x0b \x01(\x0b\x32\x0e.Reprogramming\"\x85\x01\n\rReprogramming\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x02(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\x12-\n\x05\x66lags\x18\x03 \x02(\x0e\x32\x14.Reprogramming.Flags:\x08\x43ONTINUE\"&\n\x05\x46lags\x12\x0f\n\x0bLAST_PACKET\x10\x00\x12\x0c\n\x08\x43ONTINUE\x10\x01*N\n\x06Status\x12\r\n\tHEARTBEAT\x10\x00\x12\n\n\x06IMPACT\x10\x01\x12\x16\n\x12\x45NTERING_LOW_POWER\x10\x02\x12\x11\n\rREPROGRAMMING\x10\x03'
)

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HEARTBEAT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IMPACT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENTERING_LOW_POWER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REPROGRAMMING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=395,
  serialized_end=473,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
HEARTBEAT = 0
IMPACT = 1
ENTERING_LOW_POWER = 2
REPROGRAMMING = 3


_REPROGRAMMING_FLAGS = _descriptor.EnumDescriptor(
  name='Flags',
  full_name='Reprogramming.Flags',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LAST_PACKET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONTINUE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=355,
  serialized_end=393,
)
_sym_db.RegisterEnumDescriptor(_REPROGRAMMING_FLAGS)


_LORAMSG2 = _descriptor.Descriptor(
  name='LoraMsg2',
  full_name='LoraMsg2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='LoraMsg2.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='identifier', full_name='LoraMsg2.identifier', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buildnum', full_name='LoraMsg2.buildnum', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imu', full_name='LoraMsg2.imu', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='LoraMsg2.pressure', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='LoraMsg2.temperature', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batt_voltage', full_name='LoraMsg2.batt_voltage', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='LoraMsg2.threshold', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='configuration', full_name='LoraMsg2.configuration', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rssi', full_name='LoraMsg2.rssi', index=9,
      number=10, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reprog', full_name='LoraMsg2.reprog', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=257,
)


_REPROGRAMMING = _descriptor.Descriptor(
  name='Reprogramming',
  full_name='Reprogramming',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Reprogramming.address', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='Reprogramming.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flags', full_name='Reprogramming.flags', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REPROGRAMMING_FLAGS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=393,
)

_LORAMSG2.fields_by_name['status'].enum_type = _STATUS
_LORAMSG2.fields_by_name['reprog'].message_type = _REPROGRAMMING
_REPROGRAMMING.fields_by_name['flags'].enum_type = _REPROGRAMMING_FLAGS
_REPROGRAMMING_FLAGS.containing_type = _REPROGRAMMING
DESCRIPTOR.message_types_by_name['LoraMsg2'] = _LORAMSG2
DESCRIPTOR.message_types_by_name['Reprogramming'] = _REPROGRAMMING
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoraMsg2 = _reflection.GeneratedProtocolMessageType('LoraMsg2', (_message.Message,), {
  'DESCRIPTOR' : _LORAMSG2,
  '__module__' : 'gb_messages_pb2'
  # @@protoc_insertion_point(class_scope:LoraMsg2)
  })
_sym_db.RegisterMessage(LoraMsg2)

Reprogramming = _reflection.GeneratedProtocolMessageType('Reprogramming', (_message.Message,), {
  'DESCRIPTOR' : _REPROGRAMMING,
  '__module__' : 'gb_messages_pb2'
  # @@protoc_insertion_point(class_scope:Reprogramming)
  })
_sym_db.RegisterMessage(Reprogramming)


# @@protoc_insertion_point(module_scope)
