# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gb_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gb_messages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11gb_messages.proto\"\xb9\x01\n\x08LoraMsg2\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12\x1b\n\x08gonginfo\x18\x02 \x01(\x0b\x32\t.GongInfo\x12\x1a\n\x08\x66w_setup\x18\x03 \x01(\x0b\x32\x08.FWSetup\x12\x1a\n\x06reprog\x18\x04 \x01(\x0b\x32\n.FWPackets\x12\"\n\tfw_status\x18\x05 \x01(\x0b\x32\x0f.FWUpdateStatus\x12\x1b\n\x03\x63\x66g\x18\x06 \x01(\x0b\x32\x0e.Configuration\"\xae\x01\n\x08GongInfo\x12\x0e\n\x06\x64\x65v_id\x18\x01 \x01(\r\x12\x10\n\x08\x62uildnum\x18\x02 \x01(\r\x12\x0b\n\x03imu\x18\x03 \x01(\x0c\x12\x10\n\x08pressure\x18\x04 \x01(\r\x12\x13\n\x0btemperature\x18\x05 \x01(\x11\x12\x14\n\x0c\x62\x61tt_voltage\x18\x06 \x01(\r\x12\x11\n\tthreshold\x18\x07 \x01(\r\x12\x15\n\rconfiguration\x18\x08 \x01(\r\x12\x0c\n\x04rssi\x18\t \x01(\x11\"\"\n\rConfiguration\x12\x11\n\tthreshold\x18\x01 \x01(\r\"x\n\x07\x46WSetup\x12\x15\n\rstart_address\x18\x01 \x01(\r\x12\x15\n\rtotal_packets\x18\x02 \x01(\r\x12\x18\n\x10\x62ytes_per_packet\x18\x03 \x01(\r\x12\x15\n\rfw_image_size\x18\x04 \x01(\r\x12\x0e\n\x06\x66w_crc\x18\x05 \x01(\r\")\n\tFWPackets\x12\x0e\n\x06packet\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\xb7\x01\n\x0e\x46WUpdateStatus\x12(\n\x06status\x18\x01 \x01(\x0e\x32\x18.FWUpdateStatus.FWStatus\x12\x1f\n\x17valid_packets_bit_field\x18\x02 \x01(\x0c\"Z\n\x08\x46WStatus\x12\x15\n\x11READY_FOR_PAYLOAD\x10\x00\x12\x13\n\x0fMISSING_PACKETS\x10\x01\x12\x0f\n\x0bINVALID_CRC\x10\x02\x12\x11\n\rVALID_FW_BLOB\x10\x03*t\n\x06Status\x12\x0b\n\x07NOTHING\x10\x00\x12\r\n\tHEARTBEAT\x10\x01\x12\n\n\x06IMPACT\x10\x02\x12\x16\n\x12\x45NTERING_LOW_POWER\x10\x03\x12\x17\n\x13\x45NTER_REPROGRAMMING\x10\x04\x12\x11\n\rREPROGRAMMING\x10\x05\x62\x06proto3')
)

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOTHING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEARTBEAT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMPACT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTERING_LOW_POWER', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTER_REPROGRAMMING', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPROGRAMMING', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=773,
  serialized_end=889,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
NOTHING = 0
HEARTBEAT = 1
IMPACT = 2
ENTERING_LOW_POWER = 3
ENTER_REPROGRAMMING = 4
REPROGRAMMING = 5


_FWUPDATESTATUS_FWSTATUS = _descriptor.EnumDescriptor(
  name='FWStatus',
  full_name='FWUpdateStatus.FWStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='READY_FOR_PAYLOAD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSING_PACKETS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_CRC', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALID_FW_BLOB', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=681,
  serialized_end=771,
)
_sym_db.RegisterEnumDescriptor(_FWUPDATESTATUS_FWSTATUS)


_LORAMSG2 = _descriptor.Descriptor(
  name='LoraMsg2',
  full_name='LoraMsg2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='LoraMsg2.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gonginfo', full_name='LoraMsg2.gonginfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fw_setup', full_name='LoraMsg2.fw_setup', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reprog', full_name='LoraMsg2.reprog', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fw_status', full_name='LoraMsg2.fw_status', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cfg', full_name='LoraMsg2.cfg', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=207,
)


_GONGINFO = _descriptor.Descriptor(
  name='GongInfo',
  full_name='GongInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dev_id', full_name='GongInfo.dev_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buildnum', full_name='GongInfo.buildnum', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imu', full_name='GongInfo.imu', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='GongInfo.pressure', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='GongInfo.temperature', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batt_voltage', full_name='GongInfo.batt_voltage', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='GongInfo.threshold', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='configuration', full_name='GongInfo.configuration', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rssi', full_name='GongInfo.rssi', index=8,
      number=9, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=384,
)


_CONFIGURATION = _descriptor.Descriptor(
  name='Configuration',
  full_name='Configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='threshold', full_name='Configuration.threshold', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=420,
)


_FWSETUP = _descriptor.Descriptor(
  name='FWSetup',
  full_name='FWSetup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_address', full_name='FWSetup.start_address', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_packets', full_name='FWSetup.total_packets', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes_per_packet', full_name='FWSetup.bytes_per_packet', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fw_image_size', full_name='FWSetup.fw_image_size', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fw_crc', full_name='FWSetup.fw_crc', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=542,
)


_FWPACKETS = _descriptor.Descriptor(
  name='FWPackets',
  full_name='FWPackets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet', full_name='FWPackets.packet', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='FWPackets.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=544,
  serialized_end=585,
)


_FWUPDATESTATUS = _descriptor.Descriptor(
  name='FWUpdateStatus',
  full_name='FWUpdateStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='FWUpdateStatus.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid_packets_bit_field', full_name='FWUpdateStatus.valid_packets_bit_field', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FWUPDATESTATUS_FWSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=588,
  serialized_end=771,
)

_LORAMSG2.fields_by_name['status'].enum_type = _STATUS
_LORAMSG2.fields_by_name['gonginfo'].message_type = _GONGINFO
_LORAMSG2.fields_by_name['fw_setup'].message_type = _FWSETUP
_LORAMSG2.fields_by_name['reprog'].message_type = _FWPACKETS
_LORAMSG2.fields_by_name['fw_status'].message_type = _FWUPDATESTATUS
_LORAMSG2.fields_by_name['cfg'].message_type = _CONFIGURATION
_FWUPDATESTATUS.fields_by_name['status'].enum_type = _FWUPDATESTATUS_FWSTATUS
_FWUPDATESTATUS_FWSTATUS.containing_type = _FWUPDATESTATUS
DESCRIPTOR.message_types_by_name['LoraMsg2'] = _LORAMSG2
DESCRIPTOR.message_types_by_name['GongInfo'] = _GONGINFO
DESCRIPTOR.message_types_by_name['Configuration'] = _CONFIGURATION
DESCRIPTOR.message_types_by_name['FWSetup'] = _FWSETUP
DESCRIPTOR.message_types_by_name['FWPackets'] = _FWPACKETS
DESCRIPTOR.message_types_by_name['FWUpdateStatus'] = _FWUPDATESTATUS
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoraMsg2 = _reflection.GeneratedProtocolMessageType('LoraMsg2', (_message.Message,), dict(
  DESCRIPTOR = _LORAMSG2,
  __module__ = 'gb_messages_pb2'
  # @@protoc_insertion_point(class_scope:LoraMsg2)
  ))
_sym_db.RegisterMessage(LoraMsg2)

GongInfo = _reflection.GeneratedProtocolMessageType('GongInfo', (_message.Message,), dict(
  DESCRIPTOR = _GONGINFO,
  __module__ = 'gb_messages_pb2'
  # @@protoc_insertion_point(class_scope:GongInfo)
  ))
_sym_db.RegisterMessage(GongInfo)

Configuration = _reflection.GeneratedProtocolMessageType('Configuration', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATION,
  __module__ = 'gb_messages_pb2'
  # @@protoc_insertion_point(class_scope:Configuration)
  ))
_sym_db.RegisterMessage(Configuration)

FWSetup = _reflection.GeneratedProtocolMessageType('FWSetup', (_message.Message,), dict(
  DESCRIPTOR = _FWSETUP,
  __module__ = 'gb_messages_pb2'
  # @@protoc_insertion_point(class_scope:FWSetup)
  ))
_sym_db.RegisterMessage(FWSetup)

FWPackets = _reflection.GeneratedProtocolMessageType('FWPackets', (_message.Message,), dict(
  DESCRIPTOR = _FWPACKETS,
  __module__ = 'gb_messages_pb2'
  # @@protoc_insertion_point(class_scope:FWPackets)
  ))
_sym_db.RegisterMessage(FWPackets)

FWUpdateStatus = _reflection.GeneratedProtocolMessageType('FWUpdateStatus', (_message.Message,), dict(
  DESCRIPTOR = _FWUPDATESTATUS,
  __module__ = 'gb_messages_pb2'
  # @@protoc_insertion_point(class_scope:FWUpdateStatus)
  ))
_sym_db.RegisterMessage(FWUpdateStatus)


# @@protoc_insertion_point(module_scope)
