/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev */

#include "gb_messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LoraMsg2, LoraMsg2, 2)


PB_BIND(GongInfo, GongInfo, AUTO)


PB_BIND(Configuration, Configuration, AUTO)


PB_BIND(FWSetup, FWSetup, AUTO)


PB_BIND(FWPackets, FWPackets, AUTO)


PB_BIND(FWUpdateStatus, FWUpdateStatus, AUTO)





